name: Deploy to GitHub Pages

# Define em quais eventos a ação deve ser executada
on:
  push:
    branches:
      - main  # ou master, dependendo do nome da sua branch principal

# Definindo permissões para o GITHUB_TOKEN
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Faz o checkout do repositório
      - name: Checkout the repository
        uses: actions/checkout@v2

      # (Opcional) Instale dependências ou faça build se for necessário
      # - name: Build Project
      #   run: npm install && npm run build

      # Deploy para GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # ou o diretório onde os arquivos da página estão
